all: myshell checkcpupercentage ​checkresidentmemory

myshell: myshell.c
	gcc -g myshell.c && gcc -o myshell myshell.c
	@echo "Make myshell Complete"

checkcpupercentage: checkcpupercentage.c
	gcc -g checkcpupercentage.c && gcc -o checkcpupercentage checkcpupercentage.c
	@echo "Make checkcpupercentage Complete"

​checkresidentmemory: ​checkresidentmemory.c
	gcc -g ​checkresidentmemory.c && gcc -o ​checkresidentmemory ​checkresidentmemory.c
	@echo "Make ​checkresidentmemory Complete"