all:threads nlocks

threads:threads.c
	gcc -o threads threads.c -lpthread
	@echo "Compiled threads.c successfully"

nlocks:nlocks.c
	gcc -o nlocks nlocks.c -lpthread
	@echo "Compiled nlocks.c successfully"